# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [15]:
arr1 = np.arange(10).reshape((2,5))
arr2 = np.ones(10 , dtype='int').reshape((2,5))

np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [18]:
arr1 = np.arange(10).reshape((2,5))
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
arr1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [42]:
arr1 = np.arange(15).reshape((3,5))

In [43]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
arr1.ndim

2

In [45]:
ftn_arr = arr1.ravel()

In [46]:
ftn_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
ftn_arr.ndim

1

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [49]:
arr = np.arange(15)

In [50]:
arr.ndim

1

In [51]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [54]:
arr = np.arange(25).reshape((5,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [57]:
arr = np.arange(30).reshape((5,6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
np.mean(arr)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [59]:
np.std(arr)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [60]:
np.median(arr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [61]:
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [68]:
arr = np.arange(16).reshape((4,4))
print(arr)
np.sum(np.diag(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [70]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [72]:
arr = np.arange(4).reshape((2,2))
arr

array([[0, 1],
       [2, 3]])

In [74]:
np.percentile(arr,5)         # 5th percentile

0.15000000000000002

In [75]:
np.percentile(arr,95)

2.8499999999999996

## Question:15

### How to find if a given array has any null values?

In [78]:
arr = np.array([1, 2, 0, 4, 5, 6, 0])

arr[arr == 0]   # way one so the array printed out having two null values

array([0, 0])

In [79]:
np.count_nonzero(arr)  # way two: out of 7 element only five are nonzero and 2 are zero

5